"""
Biigle volume upload for Spyfish Aotearoa.

Two-step workflow:
  1. upload_frames_to_s3()   — push extracted JPEGs to the S3 bucket Biigle has access to
  2. create_biigle_volume()  — create an image volume in Biigle pointing at that S3 folder

Ported and structured from:
  Spyfish-Aotearoa-toolkit_old/notebooks/biigle_uploader.ipynb
"""

import json
import logging
import re
from pathlib import Path
from typing import Optional

import pandas as pd

from spyfish.biigle.biigle_handler import BiigleHandler
from spyfish.config.wrapper import config
from spyfish.database.manager import DatabaseManager


def _get_survey_id(drop_id: str) -> str:
    """Derive survey ID from drop_id (e.g. 'KSF_20240124_BUV' from 'KSF_20240124_BUV_RIK_001_01').
    Uses regex for robustness; falls back to first 16 chars if pattern doesn't match.
    """
    match = re.match(r"^([A-Z]{3}_\d{8}_BUV)", drop_id)
    return match.group(1) if match else drop_id[:16]


# ── Step 1: S3 upload ────────────────────────────────────────────────────────


def upload_frames_to_s3(
    frames_df: pd.DataFrame,
    s3_frames_prefix: str,
) -> list[str]:
    """
    Upload extracted JPEG frames to S3 so Biigle can access them via the disk mount.

    Args:
        frames_df: DataFrame with a 'FramePath' column (output of extract_frames_from_selections).
                   Rows with None FramePath (extraction failures) are skipped.
        s3_frames_prefix: S3 key prefix for the upload destination, e.g.
                          "biigle_frames/KSF_20240124_BUV_KSF_085_01/"

    Returns:
        List of uploaded filenames (basename only, as used in the Biigle volume file list).
    """
    try:
        from spyfish.storage.s3_handler import S3Handler
    except ImportError:
        raise ImportError("spyfish.storage.s3_handler is required for S3 uploads.")

    s3 = S3Handler()
    uploaded = []

    frame_paths = frames_df["FramePath"].dropna().tolist()
    if not frame_paths:
        logging.warning("No frame paths to upload (all extractions may have failed).")
        return []

    for local_path in frame_paths:
        p = Path(local_path)
        if not p.exists():
            logging.warning(f"Frame not found, skipping: {local_path}")
            continue

        s3_key = s3_frames_prefix.rstrip("/") + "/" + p.name
        s3.upload_file_to_s3(str(p), key=s3_key, content_type="image/jpeg")
        uploaded.append(p.name)
        logging.info(f"  Uploaded {p.name} → s3://{s3_key}")

    logging.info(
        f"Uploaded {len(uploaded)}/{len(frame_paths)} frames to S3 prefix '{s3_frames_prefix}'"
    )
    return uploaded


# ── Step 2: Biigle volume creation ───────────────────────────────────────────


def create_biigle_volume(
    drop_id: str,
    s3_frames_prefix: str,
    file_names: list[str],
    project_id: Optional[int] = None,
) -> dict:
    """
    Create a Biigle image volume pointing at the S3 folder containing extracted frames.

    The S3 folder must be accessible via the Biigle disk configuration
    (disk-{biigle_disk_id}://{s3_frames_prefix}).

    Args:
        drop_id: Deployment identifier, used as the volume name.
        s3_frames_prefix: S3 key prefix matching what was uploaded (e.g.
                          "biigle_frames/KSF_20240124_BUV_KSF_085_01/").
        file_names: List of JPEG filenames within the S3 prefix (basenames only).
        project_id: Biigle project ID. Defaults to config.biigle_project_id.

    Returns:
        Volume info dict from the Biigle API.
    """
    if not file_names:
        raise ValueError("No files to create a Biigle volume with.")

    handler = BiigleHandler()
    s3_url = handler.build_s3_url(s3_frames_prefix)
    volume_name = f"{drop_id} — ML frames"

    logging.info(
        f"Creating Biigle image volume '{volume_name}' "
        f"with {len(file_names)} frames at {s3_url}"
    )
    volume_info = handler.create_volume_from_s3_files(
        volume_name=volume_name,
        s3_url=s3_url,
        files=file_names,
        project_id=project_id,  # type: ignore
        media_type="image",
    )
    volume_id = volume_info.get("id", "?")
    logging.info(
        f"Volume created: id={volume_id}  url=https://biigle.de/volumes/{volume_id}"
    )
    return volume_info


# ── Step 3: Annotation Upload ────────────────────────────────────────────────


def upload_coco_annotations_to_biigle(
    volume_id: int,
    coco_json_path: str,
    label_id: int = config.default_fish_label_id,
) -> dict:
    """
    Read a COCO annotations JSON file (generated by extract_frames_from_selections),
    map the images to Biigle volume images, and upload the bounding boxes.
    All bboxes use `label_id` (defaults to `config.default_fish_label_id`).
    TODO: multi-species — map COCO category names to Biigle label IDs via video_labels.csv.

    Args:
        volume_id: Biigle volume ID.
        coco_json_path: Path to the drop's `_coco_annotations_for_biigle.json` file.
        label_id: The Biigle label ID to apply to all annotations. Defaults to config value.

    Returns:
        The API response dict from the bulk upload endpoint.
    """
    if not Path(coco_json_path).exists():
        logging.warning(
            f"COCO JSON not found at {coco_json_path}. Skipping annotation upload."
        )
        return {}

    with open(coco_json_path, "r") as f:
        coco_data = json.load(f)

    if not coco_data.get("annotations"):
        logging.info("No annotations found in COCO JSON.")
        return {}

    handler = BiigleHandler()

    # 1. Fetch images from the new volume to map filenames to Biigle image IDs
    volume_images = handler.get_volume_images(volume_id)
    # Map from filename to Biigle image ID
    filename_to_biigle_id = {img["filename"]: img["id"] for img in volume_images}

    # 2. Map COCO image IDs to actual filenames
    coco_img_id_to_filename = {
        img["id"]: img["file_name"] for img in coco_data.get("images", [])
    }

    # 3. Map COCO category IDs to species names
    coco_cat_id_to_name = {
        cat["id"]: cat["name"] for cat in coco_data.get("categories", [])
    }

    # 4. Load the user's mapping from config.yaml (Scientific Name -> Biigle Label ID)
    label_mapping = config.label_mapping or {}

    # 5. Build the Biigle bulk payload
    biigle_annotations = []

    for ann in coco_data["annotations"]:
        coco_img_id = ann["image_id"]
        filename = coco_img_id_to_filename.get(coco_img_id)
        if not filename:
            continue

        biigle_img_id = filename_to_biigle_id.get(filename)
        if not biigle_img_id:
            logging.warning(f"Could not find Biigle image ID for file: {filename}")
            continue

        # COCO bbox format: [x, y, w, h] -> Biigle Rectangle format: [x1, y1, x2, y1, x2, y2, x1, y2]
        x, y, w, h = ann["bbox"]

        # Coordinates are verified to be full original frame resolution (e.g. 1920x1080), no scaling needed.
        x1, y1 = float(x), float(y)
        x2, y2 = float(x + w), float(y + h)
        points = [x1, y1, x2, y1, x2, y2, x1, y2]

        # Look up species name and specific Biigle label ID
        cat_id = ann.get("category_id")
        species_name = coco_cat_id_to_name.get(cat_id, "unknown")

        # If species exists in config mapping, use its ID. Otherwise, use the fallback label_id.
        assigned_label_id = label_mapping.get(species_name, label_id)

        biigle_annotations.append(
            {
                "image_id": biigle_img_id,
                "shape_id": 5,  # 5 = Rectangle
                "points": points,
                "label_id": assigned_label_id,
                "confidence": float(ann.get("score", 1.0)),
            }
        )

    if not biigle_annotations:
        logging.warning("No annotations resolved to valid Biigle images.")
        return {}

    # 4. Upload
    result = handler.upload_image_annotations(volume_id, biigle_annotations)
    return result


# ── Combined convenience function ─────────────────────────────────────────────


def upload_frames_to_biigle(
    drop_id: str,
    frames_df: pd.DataFrame,
    project_id: Optional[int] = None,
) -> dict:
    """
    Upload extracted frames to S3 then create a Biigle image volume — full workflow.

    Args:
        drop_id: Deployment identifier.
        frames_df: DataFrame with 'FramePath' column (from extract_frames_from_selections).
        s3_frames_prefix: S3 key prefix for the frame folder, e.g.
                          "biigle_frames/KSF_20240124_BUV_KSF_085_01/"
        project_id: Biigle project ID. Defaults to config.biigle_project_id.

    Returns:
        Biigle volume info dict (contains 'id', 'name', etc.)
    """
    logging.info(f"Starting Biigle upload for drop {drop_id}")

    # Build S3 prefix: {base_prefix}/{survey_id}/{drop_id}/
    survey_id = _get_survey_id(drop_id)
    s3_prefix = f"{config.biigle_s3_images_prefix}/{survey_id}/{drop_id}/"

    # Step 1: Upload frames to S3
    file_names = upload_frames_to_s3(frames_df, s3_prefix)

    if not file_names:
        raise RuntimeError(
            f"No frames uploaded to S3 for {drop_id} — aborting volume creation."
        )

    # Step 2: Create Biigle volume
    volume_info = create_biigle_volume(drop_id, s3_prefix, file_names, project_id)
    volume_id = volume_info.get("id")

    if volume_id:
        logging.info(
            f"✅ Biigle Volume Created! Link: https://biigle.de/projects/{project_id or config.biigle_project_id}/volumes/{volume_id}"
        )

    # Step 3: Save volume_id to database
    if volume_id:
        db = DatabaseManager()
        db.update_biigle_volume_id(drop_id, volume_id)
        logging.info(f"Saved Biigle volume_id {volume_id} to database for {drop_id}")

    # Step 4: Upload COCO bounding box annotations to the new volume
    # The JSON lives in the drop's annotation folder
    annotations_dir = config.get_drop_annotations_dir(drop_id)
    coco_json_path = annotations_dir / f"{drop_id}_coco_annotations_for_biigle.json"

    if volume_id and coco_json_path.exists():
        upload_coco_annotations_to_biigle(volume_id, str(coco_json_path))

    return volume_info
