name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_docs.sh
        run: |
          chmod +x ./generate_docs.sh
          ./generate_docs.sh

      - name: Commit generated docs to the repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update generated docs"
          git push origin main
