name: Generate Documentation

on:
  workflow_dispatch:
  # TODO add schedule or triggers future if necessary:
  # schedule:
  #   - cron: '0 3 * * 0'
  # push:
  #   branches:
  #     - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: docs
          fetch-depth: 0

      - name: Run generate_docs.sh
        run: |
          chmod +x ./generate_docs.sh
          ./generate_docs.sh  # Should write output to ./docs/

      - name: Commit generated docs to docs branch
        run: |
          cd docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated docs" || echo "No changes to commit"
          git push origin docs
