name: Updates kso csv files based on latest sharepoint lists export

on:
  workflow_dispatch:
    # Allows manual triggering
  schedule:
    # Runs every Sunday at 02:00 UTC
    - cron: '0 2 * * 0'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        # Cache for pip dependencies
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy and format latest lists to kso csv files
      run: |
        python metadata_management/sharepoint_to_kso.py
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_KSO_TEST_CSV : $S3_KSO_TEST_CSV
        S3_SHAREPOINT_TEST_CSV : $S3_SHAREPOINT_TEST_CSV
        DEV_MODE : $DEV_MODE

        # TODO: hold for after testing
        # S3_SHAREPOINT_MOVIE_CSV: ${{ secrets.S3_SHAREPOINT_MOVIE_CSV }}
        # S3_SHAREPOINT_SURVEY_CSV: ${{ secrets.S3_SHAREPOINT_SURVEY_CSV }}
        # S3_SHAREPOINT_SPECIES_CSV: ${{ secrets.S3_SHAREPOINT_SPECIES_CSV }}
        # S3_KSO_MOVIE_CSV: ${{ secrets.S3_KSO_MOVIE_CSV }}
        # S3_SHAREPOINT_SITE_CSV: ${{ secrets.S3_SHAREPOINT_SITE_CSV }}
        # S3_KSO_SURVEY_CSV: ${{ secrets.S3_KSO_SURVEY_CSV }}
        # S3_KSO_SITE_CSV: ${{ secrets.S3_KSO_SITE_CSV }}
        # S3_KSO_ANNOTATIONS_CSV: ${{ secrets.S3_KSO_ANNOTATIONS_CSV }}
        # S3_KSO_SPECIES_CSV: ${{ secrets.S3_KSO_SPECIES_CSV }}
